### ISSUE TITLE
请问怎么把右侧标签云呈现出来

### ISSUE THREAD

**Issue by cfdtlee** [bill-xia/hexo-theme-mashiro#3]
你好啊，谢谢你设计的主题，很简约。
我想问一下怎么设置呈现右侧最近，分类和标签云呢？
我的网站地址是blog.shuang.li

**Comment by cfdtlee** [comment]
我用landscape 主题是可以显示右侧菜单的，我比较了一下theam/_config, 也没有发现不对的地方

**Comment by bill-xia** [comment]
不好意思，这是我在自己站点上实验的内容，还没有push到github上

**Comment by bill-xia** [comment]
我现在检查一下，没有问题我就同步上来了

**Comment by cfdtlee** [comment]
太好了！感谢！

**Comment by bill-xia** [comment]
已更新。
