### ISSUE TITLE
如何置顶文章

### ISSUE THREAD

**Issue by enoche** [bill-xia/hexo-theme-mashiro#5]
RT. 谢谢！

**Comment by bill-xia** [comment]
我在develop分支下commit了一版，增加了这个功能。您可以拉取develop分支的主题代码，并在想要置顶的文章的front-matter里加一个pinned字段，写入一个整数，如下所示：

```
---
title: your title
pinned: 1
---
```

这篇文章就应当被置顶了。如果有多篇需要置顶的文章，可以设置不同的pinned值来为他们排序，pinned值小的在前。pinned值相同时按照时间顺序排序，较新的在前。

如果您测试后没问题，希望您能在这里给出反馈，我会写好文档后合并到主线里。

**Comment by bill-xia** [comment]
好像有点问题...没能全站置顶，只能把它在当前页的文章中置顶，我再改改吧。

**Comment by bill-xia** [comment]
参考这个链接：https://github.com/hexojs/hexo-generator-index#usage
兜兜转转官方都实现好了;-)
他只能在主页置顶，archive页里不能置顶，不知道能否满足您的需求。

**Comment by enoche** [comment]
非常感谢，我试试！

**Comment by enoche** [comment]
> 参考这个链接：https://github.com/hexojs/hexo-generator-index#usage 兜兜转转官方都实现好了;-) 他只能在主页置顶，archive页里不能置顶，不知道能否满足您的需求。

这个主页置顶，我估计得在另一个账号中试试，回头我反馈您！

**Comment by xinzhou-ai** [comment]
我测试了下：发现没有办法直接hexo g生成静态文件


ERROR
TypeError: C:github.io\themes\mashiro\layout\layout.ejs:17
    15|     </div>
    16|     <%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %>
 >> 17|     <%- partial('_partial/after-footer') %>

C:\.github.io\themes\mashiro\layout\_partial\after-footer.ejs:25
    23| <%- partial('gauges-analytics') %>
    24|
 >> 25| <% if(theme.valine.enable && theme.valine.appId && theme.valine.appKey){ %>
    26|   <%- js('https://cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js') %>
    27| <script>
    28|     var GUEST_INFO = ['nick','mail','link'];

Cannot read properties of undefined (reading 'enable')

**Comment by bill-xia** [comment]
主题配置文件里的valine那一项是不是被删掉了？把它按照_config.sample.yml加回来试试

**Comment by xinzhou-ai** [comment]
> 主题配置文件里的valine那一项是不是被删掉了？把它按照_config.sample.yml加回来试试

没有删除，按sample原copy，加上theme, 可能是layout那边文件有问题~

**Comment by bill-xia** [comment]
我在develop分支里改了一下，不再需要显式配置valine了，您拉下develop分支再试试

**Comment by xinzhou-ai** [comment]
> 我在develop分支里改了一下，不再需要显式配置valine了，您拉下develop分支再试试

嗯，搞定了！   原来是我改了 主目录下的_config.yml，没有修改themes/mashiro/下面的_config.yml


对了，文章的 READMORE 您怎么实现的？ 默认 每篇文章都全铺 在主页了。

**Comment by bill-xia** [comment]
看这里 https://github.com/bill-xia/hexo-theme-mashiro#摘要

**Comment by xinzhou-ai** [comment]
> 看这里 [https://github.com/bill-xia/hexo-theme-mashiro#摘要](https://github.com/bill-xia/hexo-theme-mashiro#%E6%91%98%E8%A6%81)

OK, 可以的，非常感谢！ 我玩玩这个主题~
