### ISSUE TITLE
在标题使用中文标点会导致排版错误

### ISSUE THREAD

**Issue by lixiangwuxian** [bill-xia/hexo-theme-mashiro#7]
中文标点会转译为诸如`<span class="bd-box">$1</span>`这样的对应标签段，但是这样的标签段在标题对应的html标签中变为
``` html
<h1 id="xxx<span class="bd-box">$1</span>">
```
导致解析出的html格式与预期不同。
应该需要在transpunc.js中额外实现对是否为标题的判断

**Comment by bill-xia** [comment]
ok，问题我明白了，我思考一下怎么解决

**Comment by bill-xia** [comment]
已修复，是markdown renderer的问题，将标题内容作为`<h1>`标签的id而没有转义。

要看到修复效果，运行：

``` bash
npm update markdown-them
hexo clean
hexo s
```

如果没有修复可以继续联系我。

**Comment by lixiangwuxian** [comment]
感谢回答，稍等我去尝试一下

**Comment by lixiangwuxian** [comment]
感谢，问题已解决
